# Generated by Django 5.1.5 on 2025-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='workout_type',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('full_body', 'Full Body'), ('upper_body', 'Haut du corps'), ('lower_body', 'Bas du corps'), ('arms', 'Bras'), ('legs', 'Jambes'), ('shoulders', 'Epaules'), ('chest', 'Pecs'), ('cardio', 'Cardio'), ('strength', 'Force')], max_length=20),
        ),
    ]
