# Generated by Django 5.1.5 on 2025-05-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=6)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('name', models.CharField(choices=[('weight_loss', 'Perte de poids'), ('muscle_gain', 'Prise de masse'), ('maintenance', 'Maintien')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('recurrence_period', models.IntegerField(blank=True, choices=[(1, 'Mensuel'), (3, 'Trimestriel'), (6, 'Semestriel')], null=True)),
                ('workout_type', models.CharField(choices=[('full_body', 'Full Body'), ('upper_body', 'Haut du corps'), ('lower_body', 'Bas du corps'), ('arms', 'Bras'), ('legs', 'Jambes'), ('shoulders', 'Epaules'), ('chest', 'Pecs'), ('height loss', 'Perte de poids'), ('weight gain', 'Prise de poids'), ('maintenance', 'Maintien'), ('cardio', 'Cardio'), ('flexibility', 'Flexibilité'), ('balance', 'Équilibre'), ('endurance', 'Endurance'), ('strength', 'Force'), ('power', 'Puissance'), ('speed', 'Vitesse'), ('agility', 'Agilité')], default='full_body', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('full_body', 'Full Body'), ('upper_body', 'Haut du corps'), ('lower_body', 'Bas du corps'), ('arms', 'Bras'), ('legs', 'Jambes'), ('shoulders', 'Epaules'), ('chest', 'Pecs'), ('height loss', 'Perte de poids'), ('weight gain', 'Prise de poids'), ('maintenance', 'Maintien'), ('cardio', 'Cardio'), ('flexibility', 'Flexibilité'), ('balance', 'Équilibre'), ('endurance', 'Endurance'), ('strength', 'Force'), ('power', 'Puissance'), ('speed', 'Vitesse'), ('agility', 'Agilité')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('equipment_needed', models.TextField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.goal')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('meals', models.TextField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='programs.goal')),
            ],
        ),
    ]
