# Generated by Django 5.2 on 2025-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="poids",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="taille",
            field=models.FloatField(null=True),
        ),
    ]
