# Generated by Django 5.2 on 2025-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Homme", "Homme"), ("Femme", "Femme"), ("Autre", "Autre")],
                max_length=10,
            ),
        ),
    ]
