# Generated by Django 5.2 on 2025-05-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="imc",
            field=models.FloatField(null=True),
        ),
    ]
