# Generated by Django 5.2 on 2025-05-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="subscription_plans/"
            ),
        ),
    ]
